feat: partial implements gas report for ethereum watcher service
SlowlyCloud/ethereum-watcher pull request #1
Opened 2023-12-16 06:01 UTC by nnmax

2023-12-17 13:43 UTC, rickliujh reviewed
1. files' name should meaningful, e.g. align with domain
2. how do you manage the state change after? do you need a state management class or state machine?
3. timeout is mandatory if pushNotification is specified. should we need any sanity check in controller in order to prevent any unexpected behaviour from service?

2023-12-17 14:12 UTC, rickliujh commented
I have made some update in docs in terms of target's design. you might need to know before merge this pr.
https://github.com/SlowlyCloud/docs/pull/2

2023-12-27 18:42 UTC, rickliujh requested changes

2023-12-27 18:42 UTC, rickliujh commented on src/ethereumWatcher/ethereumWatcher.service.ts
> +            gasReport.pushNotification = data.args.pushNotification;
you might want to apply builder pattern here to assign the DTO

2023-12-27 18:42 UTC, rickliujh commented on src/ethereumWatcher/rest/ethereumWatcher.controller.ts
> +    @Delete('gas-report/:id')
@Post()
@Delete(':id')

are able to replace to for simplify

and @Controller can be change below accordingly

@Controller("v1/gas-report")

2023-12-27 18:42 UTC, rickliujh commented on src/ethereumWatcher/queries/transactions.handle.ts
> +    private readonly alchemy = new Alchemy({
normally, the assign of variable with construction should happen in the constructer of class itself or through injection from dependency container.

2023-12-27 18:42 UTC, rickliujh commented on src/ethereumWatcher/queries/transactions.handle.ts
> +            'InquiryApeHandle::execute:document:' + JSON.stringify(document),
code that commit at least should able to pass the compiler

2023-12-27 18:42 UTC, rickliujh commented on src/ethereumWatcher/rest/ethereumWatcher.dto.ts
> +class Target {
the Target class doesn't follow the struct defined in https://github.com/SlowlyCloud/docs/pull/2

2023-12-27 18:42 UTC, rickliujh commented on src/ethereumWatcher/rest/ethereumWatcher.dto.ts
> +    @Type(() => Number)
is able to remove this line? it should work just fine with two assertion below.

2023-12-27 18:42 UTC, rickliujh commented on src/ethereumWatcher/ethereumWatcher.service.ts
> +        const pendingTransactionsListener = (
is possible keep this function as the method of class in order to reduce this memory allocate from every time calling this function due to the repeated creation of same listener?

2023-12-27 18:43 UTC, rickliujh commented
> * files' name should meaningful, e.g. align with domain
> * how do you manage the state change after? do you need a state management class or state machine?
> * timeout is mandatory if pushNotification is specified. should we need any sanity check in controller in order to prevent any unexpected behaviour from service?

and please don't forget to solve these as well. 

Thank you for PR

2024-01-03 07:23 UTC, nnmax commented
> 1. files' name should meaningful, e.g. align with domain
> 
>     2. how do you manage the state change after? do you need a state management class or state machine?
> 
>     3. timeout is mandatory if pushNotification is specified. should we need any sanity check in controller in order to prevent any unexpected behaviour from service?

Sorry, I don't quite understand the first and second points.

All other issues have been fixed.

2024-01-03 14:45 UTC, rickliujh commented on src/ethereumWatcher/websocket/ethereumWatcher.websocket.ts
> +        this.ws.server.emit('EW:HIGHEST_GAS', {});
I think the name of event GAS_REPORT is better for this case

2024-01-03 14:45 UTC, rickliujh commented on src/ethereumWatcher/rest/ethereumWatcher.controller.ts
> +export class EthereumWatcherController {
What do you think to name this controller to "GasReportController"?

2024-01-03 14:56 UTC, rickliujh commented
> > 1. files' name should meaningful, e.g. align with domain
> >    
> >    2. how do you manage the state change after? do you need a state management class or state machine?
> >    3. timeout is mandatory if pushNotification is specified. should we need any sanity check in controller in order to prevent any unexpected behaviour from service?
> 
> Sorry, I don't quite understand the first and second points.
> 
> All other issues have been fixed.

Sounds good. 

By what I mean in first one "meaningful" is to name a file with respects to its domain logic, so it will clear for other developers to read and understand. The file `ethereumWatcher.controller.ts` might feel more concise as the name `gasReport.controller.ts` than just repeating the service name, for example.

For the second one, I'm suggesting that we should maintain the state of transaction (by doing so, we should store the state in DB), so we will know how the gas change from time to time, like the gas growth from 12eth 2023-12-31 to 14eth 2024-1-1 in the sequence

2024-01-04 17:18 UTC, rickliujh reviewed
shall we change name of ethereumWatcher.service.ts as well

2024-01-05 04:07 UTC, nnmax commented
> shall we change name of ethereumWatcher.service.ts as well

done

2024-01-05 16:17 UTC, rickliujh approved these changes

2024-01-07 02:32 UTC, merged